---
logging:
  level:
    root: WARN

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    default: production

server:
  address: 0.0.0.0
  port: ${PORT:8080}

sentry:
  dsn: ${SENTRY_DSN:}
  traces-sample-rate: 1.0

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
