name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: 'build checkstyleMain checkstyleTest'
          gradle-version: 8.7
          build-root-directory: app
      - name: Run tests and generate JaCoCo report
        run: report
      - name: Publish code coverage
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.CC_TEST_REPORTER_ID }}
          files: app/build/reports/jacoco/test/jacocoTestReport.xml
